[project]
name = "event-aggregator"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = [
    "E",
    "F",     # неиспользуемые импорты и переменные
    "I",     # сортировка импортов
    "B",     # потенциальные ошибки
    "UP",    # современный синтаксис Python
    "ASYNC", # ошибки в асинхронном коде
    "FAST",  # специальные проверки FastAPI
    "RUF",   # собственные проверки Ruff
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
