name: Code checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v7

      - name: Install uv and Python
        uses: astral-sh/setup-uv@v9
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Check code
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .