"""create_tables

Revision ID: 57cc8980a41a
Revises: cb941354ed01
Create Date: 2026-09-09 22:06:47.912654

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57cc8980a41a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("seats_pattern", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_places_changed_at"), "places", ["changed_at"], unique=False)
    op.create_index(op.f("ix_places_city"), "places", ["city"], unique=False)
    op.create_index(op.f("ix_places_created_at"), "places", ["created_at"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("place_id", sa.UUID(), nullable=True),
        sa.Column("number_of_visitors", sa.Integer(), nullable=False),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["place_id"], ["places.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_changed_at"), "events", ["changed_at"], unique=False)
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_event_time"), "events", ["event_time"], unique=False)
    op.create_index(op.f("ix_events_place_id"), "events", ["place_id"], unique=False)
    op.create_index(
        op.f("ix_events_registration_deadline"), "events", ["registration_deadline"], unique=False
    )
    op.create_index(
        op.f("ix_events_status_changed_at"), "events", ["status_changed_at"], unique=False
    )
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("seat", sa.String(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "seat", name="uq_ticket_event_seat"),
    )
    op.create_index(op.f("ix_tickets_created_at"), "tickets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tickets_email"), "tickets", ["email"], unique=False)
    op.create_index(op.f("ix_tickets_event_id"), "tickets", ["event_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_event_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_email"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_at"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_events_status_changed_at"), table_name="events")
    op.drop_index(op.f("ix_events_registration_deadline"), table_name="events")
    op.drop_index(op.f("ix_events_place_id"), table_name="events")
    op.drop_index(op.f("ix_events_event_time"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_index(op.f("ix_events_changed_at"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_places_created_at"), table_name="places")
    op.drop_index(op.f("ix_places_city"), table_name="places")
    op.drop_index(op.f("ix_places_changed_at"), table_name="places")
    op.drop_table("places")
    # ### end Alembic commands ###
