"""create tables

Revision ID: dd3ea4e0b030
Revises:
Create Date: 2026-09-09 09:34:34.048500

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd3ea4e0b030"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guests",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "locations",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_locations_created_at"), "locations", ["created_at"], unique=False)
    op.create_table(
        "events",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location_uuid", sa.UUID(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=False),
        sa.Column("registration_deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_uuid"], ["locations.uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_events_created_at"), "events", ["created_at"], unique=False)
    op.create_index(op.f("ix_events_location_uuid"), "events", ["location_uuid"], unique=False)
    op.create_index(
        op.f("ix_events_registration_deadline"), "events", ["registration_deadline"], unique=False
    )
    op.create_index(op.f("ix_events_time"), "events", ["time"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("event_uuid", sa.UUID(), nullable=False),
        sa.Column("guest_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["event_uuid"], ["events.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["guest_uuid"], ["guests.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_tickets_created_at"), "tickets", ["created_at"], unique=False)
    op.create_index(op.f("ix_tickets_event_uuid"), "tickets", ["event_uuid"], unique=False)
    op.create_index(op.f("ix_tickets_guest_uuid"), "tickets", ["guest_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tickets_guest_uuid"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_event_uuid"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_created_at"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_events_time"), table_name="events")
    op.drop_index(op.f("ix_events_registration_deadline"), table_name="events")
    op.drop_index(op.f("ix_events_location_uuid"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_locations_created_at"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("guests")
    # ### end Alembic commands ###
