name: Code checks

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv and Python
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Check code
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check .
